[phases.setup]
nixPkgs = ["cabal-install", "ghc", "zlib", "zlib.dev", "pkg-config", "ncurses", "binutils"]

[phases.build]
cmds = [
  "cabal update",
  # We combine build, copy, and purge into ONE single shell command
  """
  cabal build --extra-include-dirs=$(pkg-config --variable=includedir zlib) \
              --extra-lib-dirs=$(pkg-config --variable=libdir zlib) \
              --jobs=1 --disable-optimization && \
  mkdir -p ./output && \
  cp $(cabal list-bin imd-server) ./output/imd-server && \
  strip ./output/imd-server && \
  rm -rf dist-newstyle /root/.cabal /root/.ghc
  """
]

[start]
# We run the isolated binary from our tiny output folder
cmd = "./output/imd-server"

[variables]
PKG_CONFIG_PATH = "$PKG_CONFIG_PATH:/nix/var/nix/profiles/default/lib/pkgconfig"
LD_LIBRARY_PATH = "$LD_LIBRARY_PATH:/nix/var/nix/profiles/default/lib"