[phases.setup]
nixPkgs = ["ghc", "cabal-install", "zlib", "gmp", "zlib1g-dev", "libtinfo-dev", "pkg-config"] 

[phases.build]
cmds = ["cabal update", "cabal build"]

[start]
cmd = "cabal run imd-server"