name: imd-simulator
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - aeson
  - servant-server
  - warp
  - wai
  - wai-cors
  - cassava
  - vector
  - text
  - bytestring

executables:
  imd-server:
    main: Main.hs
    source-dirs: .